language: php
php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
script: "phpunit -c src/test/resources/phpunit.xml"
before_script:
  composer install --prefer-source
matrix:
  fast_finish: true
sudo: false